INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1,  'colors', 'black', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2,  'colors', 'white', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1,  'colors', 'color', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4,  'colors', 'yellow', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1,  'colors', 'purple', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5,  'colors', 'green', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6,  'colors', 'blue', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1,  'colors', 'orange', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1,  'colors', 'pink', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'circle', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'shapes', 'square', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'triangle', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'shapes', 'rectangle', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'shapes', 'arrow', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'star', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'shapes', 'cross', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'diamond', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'shapes', 'heart', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'hexagon', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'shapes', 'oval', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'parallelogram', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'shapes', 'trapezoid', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Numbers', '0', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'Numbers', '1', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '2', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '3', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'Numbers', '4', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '5', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '6', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'Numbers', '11', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '21', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Numbers', '99', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '100', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Numbers', '1000', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '10,000', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Numbers', '100,000', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '1,000,000', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'Numbers', '1,000,000,000', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Numbers', '1,234,567,890', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Food: Fruit', 'apple', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Food: Fruit', 'banana', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Food: Fruit', 'coconut', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Food: Fruit', 'lemon', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Food: Fruit', 'pineapple', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Food: Fruit', 'strawberry', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Food: Fruit', 'watermelon', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'Food: Vegetables', 'asparagus', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Food: Vegetables', 'bellpepper', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Food: Vegetables', 'broccoli', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Food: Vegetables', 'cabbage', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Food: Vegetables', 'cauliflower', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'Food: Vegetables', 'greenbeans', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Food: Vegetables', 'onion', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Food: Vegetables', 'tomato', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'Activities', 'sleep', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Activities', 'eat', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'Activities', 'drink', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Activities', 'walk', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Activities', 'run', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Activities', 'jump', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'Activities', 'sit', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Activities', 'stand', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Activities', 'look', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Activities', 'see', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'Activities', 'listen', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Activities', 'hear', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Activities', 'speak', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Activities', 'talk', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Activities', 'say', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Days', 'Sunday', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Days', 'Monday', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'Days', 'Tuesday', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Days', 'Wednesday', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'Days', 'Thursday', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'Days', 'Friday', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'Days', 'Saturday', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'January', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Months', 'February', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'Months', 'March', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'April', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'May', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'Months', 'June', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'July', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'August', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Months', 'September', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'October', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'Months', 'November', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'Months', 'December', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Seasons', 'spring', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'Seasons', 'summer', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Seasons', 'autumn', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'Seasons', 'winter', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Weather', 'sunny', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'Weather', 'cloudy', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Weather', 'foggy', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'Weather', 'smoggy', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Weather', 'rainy', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Weather', 'windy', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'Weather', 'snowy', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'Temperature', 'hot', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'Temperature', 'warm', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Temperature', 'cool', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Temperature', 'cold', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Math', '2 + 3', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Math', '2 + 4', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'Math', '2 + 5', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'Math', '2 + 6', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'Math', '2 + 7', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'Math', '2 + 8', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Math', '2 + 9', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Math', '2 + 10', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'Math', '2 + 11', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'Math', '2 + 13', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Math', '2 + 14', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Math', '2 + 15', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Math', '2 + 16', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'Math', '2 + 18', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Math', '2 + 19', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'Math', '19 + 3', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'Math', '90 + 3', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Money', 'penny', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'Money', 'nickel', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Money', 'dime', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'Money', 'quarter', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'Money', 'half-dollar', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'Money', 'dollar coins', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'Money', 'dollar bill', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'A', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Capital Letters', 'B', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'C', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'The Alphabet: Capital Letters', 'D', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'The Alphabet: Capital Letters', 'E', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'The Alphabet: Capital Letters', 'F', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'The Alphabet: Capital Letters', 'G', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Capital Letters', 'H', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'I', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'The Alphabet: Capital Letters', 'J', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'K', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'The Alphabet: Capital Letters', 'L', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Capital Letters', 'M', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Capital Letters', 'N', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'O', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(3, 'The Alphabet: Capital Letters', 'P', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'The Alphabet: Capital Letters', 'Q', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(5, 'The Alphabet: Capital Letters', 'R', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'S', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'The Alphabet: Capital Letters', 'T', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Capital Letters', 'U', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'The Alphabet: Capital Letters', 'V', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(9, 'The Alphabet: Capital Letters', 'W', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'The Alphabet: Capital Letters', 'X', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(2, 'The Alphabet: Capital Letters', 'Y', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(1, 'The Alphabet: Capital Letters', 'Z', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'The Alphabet: Small Letters', 'A', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'The Alphabet: Small Letters', 'B', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'The Alphabet: Small Letters', 'C', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'D', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'E', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'The Alphabet: Small Letters', 'F', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'The Alphabet: Small Letters', 'G', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'The Alphabet: Small Letters', 'H', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'I', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'J', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(6, 'The Alphabet: Small Letters', 'K', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'L', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'The Alphabet: Small Letters', 'M', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'The Alphabet: Small Letters', 'N', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(4, 'The Alphabet: Small Letters', 'O', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'P', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(13, 'The Alphabet: Small Letters', 'Q', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(10, 'The Alphabet: Small Letters', 'R', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(8, 'The Alphabet: Small Letters', 'S', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'T', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(12, 'The Alphabet: Small Letters', 'U', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'V', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(14, 'The Alphabet: Small Letters', 'W', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(15, 'The Alphabet: Small Letters', 'X', false);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(7, 'The Alphabet: Small Letters', 'Y', true);
INSERT INTO "Answer" (quiz_id, category, text, correct) VALUES(11, 'The Alphabet: Small Letters', 'Z', false);
