DO $$
DECLARE CategoryID integer;
BEGIN
INSERT INTO "Category" (type, title, slug) VALUES('color', 'Colors', 'colors') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'black', '/audio/colors/black.mp3', 'black', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'white', '/audio/colors/white.mp3', 'white', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'red', '/audio/colors/red.mp3', 'red', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'yellow', '/audio/colors/yellow.mp3', 'yellow', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'green', '/audio/colors/green.mp3', 'green', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'purple', '/audio/colors/purple.mp3', 'purple', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'blue', '/audio/colors/blue.mp3', 'blue', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'orange', '/audio/colors/orange.mp3', 'orange', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'pink', '/audio/colors/pink.mp3', 'pink', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'brown', '/static/audio/colors/brown.mp3', 'brown', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'tan', '/static/audio/colors/tan.mp3', 'tan', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'gray', '/static/audio/colors/gray.mp3', 'gray', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Shapes', 'shapes') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'circle', '/audio/shapes/circle.mp3', NULL, '/images/shapes/circle.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'square', '/audio/shapes/square.mp3', NULL, '/images/shapes/square.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'triangle', '/audio/shapes/triangle.mp3', NULL, '/images/shapes/triangle.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'rectangle', '/audio/shapes/rectangle.mp3', NULL, '/images/shapes/rectangle.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'arrow', '/audio/shapes/arrow.mp3', NULL, '/images/shapes/arrow.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'star', '/audio/shapes/star.mp3', NULL, '/images/shapes/star.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cross', '/audio/shapes/cross.mp3', NULL, '/images/shapes/cross.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'diamond', '/audio/shapes/diamond.mp3', NULL, '/images/shapes/diamond.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'heart', '/audio/shapes/heart.mp3', NULL, '/images/shapes/heart.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'hexagon', '/audio/shapes/hexagon.mp3', NULL, '/images/shapes/hexagon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'moon', '/audio/shapes/moon.mp3', NULL, '/images/shapes/moon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'pentagon', '/audio/shapes/pentagon.mp3', NULL, '/images/shapes/pentagon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'octagon', '/audio/shapes/octagon.mp3', NULL, '/images/shapes/octagon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'oval', '/audio/shapes/oval.mp3', NULL, '/images/shapes/oval.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'parallelogram', '/audio/shapes/parallelogram.mp3', NULL, '/images/shapes/parallelogram.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'trapezoid', '/audio/shapes/trapezoid.mp3', NULL, '/images/shapes/trapezoid.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Numbers', 'numbers') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '0', '/audio/numbers/zero.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1', '/audio/numbers/one.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2', '/audio/numbers/two.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3', '/audio/numbers/three.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4', '/audio/numbers/four.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5', '/audio/numbers/five.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '6', '/audio/numbers/six.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '11', '/audio/numbers/eleven.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '21', '/audio/numbers/twentyone.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '99', '/audio/numbers/ninetynine.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '100', '/audio/numbers/onehundred.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1000', '/audio/numbers/onethousand.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '10,000', '/audio/numbers/tenthousand.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '100,000', '/audio/numbers/onehundredthousand.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1,000,000', '/audio/numbers/onemillion.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1,000,000,000', '/audio/numbers/onebillion.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1,234,567,890', '/audio/numbers/1234567890.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Food: Fruit', 'food-fruit') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'apple', '/audio/food/fruit/apple.mp3', NULL, '/images/food/fruit/apple.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'banana', '/audio/food/fruit/banana.mp3', NULL, '/images/food/fruit/banana.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'coconut', '/audio/food/fruit/coconut.mp3', NULL, '/images/food/fruit/coconut.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'lemon', '/audio/food/fruit/lemon.mp3', NULL, '/images/food/fruit/lemon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'pineapple', '/audio/food/fruit/pineapple.mp3', NULL, '/images/food/fruit/pineapple.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'strawberry', '/audio/food/fruit/strawberry.mp3', NULL, '/images/food/fruit/strawberry.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'watermelon', '/audio/food/fruit/watermelon.mp3', NULL, '/images/food/fruit/watermelon.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Food: Vegetables', 'food-vegetables') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'asparagus', '/audio/food/vegetables/asparagus.mp3', NULL, '/images/food/vegetables/asparagus.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'bellpepper', '/audio/food/vegetables/bellpepper.mp3', NULL, '/images/food/vegetables/bellpepper.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'broccoli', '/audio/food/vegetables/broccoli.mp3', NULL, '/images/food/vegetables/broccoli.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cabbage', '/audio/food/vegetables/cabbage.mp3', NULL, '/images/food/vegetables/cabbage.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cauliflower', '/audio/food/vegetables/cauliflower.mp3', NULL, '/images/food/vegetables/cauliflower.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'greenbeans', '/audio/food/vegetables/greenbeans.mp3', NULL, '/images/food/vegetables/greenbeans.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'onion', '/audio/food/vegetables/onion.mp3', NULL, '/images/food/vegetables/onion.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'spinach', '/audio/food/vegetables/spinach.mp3', NULL, '/images/food/vegetables/spinach.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'tomato', '/audio/food/vegetables/tomato.mp3', NULL, '/images/food/vegetables/tomato.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Activities', 'activities') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'sleep', '/audio/activities/sleep.mp3', NULL, '/images/activities/sleep.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'eat', '/audio/activities/eat.mp3', NULL, '/images/activities/eat.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'drink', '/audio/activities/drink.mp3', NULL, '/images/activities/drink.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'walk', '/audio/activities/walk.mp3', NULL, '/images/activities/walk.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'run', '/audio/activities/run.mp3', NULL, '/images/activities/run.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'jump', '/audio/activities/jump.mp3', NULL, '/images/activities/jump.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'sit', '/audio/activities/sit.mp3', NULL, '/images/activities/sit.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'stand', '/audio/activities/stand.mp3', NULL, '/images/activities/stand.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'look', '/audio/activities/look.mp3', NULL, '/images/activities/look-see.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'listen', '/audio/activities/listen.mp3', NULL, '/images/activities/listen-hear.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'speak', '/audio/activities/speak.mp3', NULL, '/images/activities/speak-talk-say.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Days of the week', 'days-of-the-week') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Sunday', '/audio/days/Sunday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Monday', '/audio/days/Monday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Tuesday', '/audio/days/Tuesday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Wednesday', '/audio/days/Wednesday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Thursday', '/audio/days/Thursday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Friday', '/audio/days/Friday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Saturday', '/audio/days/Saturday.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Days', 'days') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'today', '/audio/days/today.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'tomorrow', '/audio/days/tomorrow.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'yesterday', '/audio/days/yesterday.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'the day after tomorrow', '/audio/days/dayaftertomorrow.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'the day before yesterday', '/audio/days/daybeforeyesterday.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Months', 'months') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'January', '/audio/months/January.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'February', '/audio/months/February.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'March', '/audio/months/March.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'April', '/audio/months/April.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'May', '/audio/months/May.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'June', '/audio/months/June.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'July', '/audio/months/July.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'August', '/audio/months/August.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'September', '/audio/months/September.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'October', '/audio/months/October.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'November', '/audio/shapes/November.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'December', '/audio/shapes/December.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Seasons', 'seasons') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'spring', '/audio/seasons-temp-weather/spring.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'summer', '/audio/seasons-temp-weather/summer.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'autumn', '/audio/seasons-temp-weather/autumn.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'winter', '/audio/seasons-temp-weather/winter.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Weather', 'weather') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'sunny', '/audio/seasons-temp-weather/sunny.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cloudy', '/audio/seasons-temp-weather/cloudy.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'foggy', '/audio/seasons-temp-weather/foggy.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'smoggy', '/audio/seasons-temp-weather/smoggy.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'rainy', '/audio/seasons-temp-weather/rainy.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'windy', '/audio/seasons-temp-weather/windy.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'snowy', '/audio/seasons-temp-weather/snowy.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Temperature', 'temperature') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'hot', '/audio/seasons-temp-weather/hot.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'warm', '/audio/seasons-temp-weather/warm.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cool', '/audio/seasons-temp-weather/cool.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cold', '/audio/seasons-temp-weather/cold.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Math', 'math') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 2', '/static/audio/math/twoplus2.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 3', '/audio/math/2plus3.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 4', '/audio/math/2plus4.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 5', '/audio/math/2plus5.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 6', '/audio/math/2plus6.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 7', '/audio/math/2plus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 8', '/audio/math/2plus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 9', '/audio/math/2plus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 10', '/audio/math/2plus10.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 11', '/audio/math/2plus11.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 12', '/static/audio/math/twoplus12.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 13', '/audio/math/2plus13.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 14', '/audio/math/2plus14.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 15', '/audio/math/2plus15.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 16', '/audio/math/2plus16.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 18', '/audio/math/2plus18.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 19', '/audio/math/2plus19.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 3', '/static/audio/math/threeplus3.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 4', '/static/audio/math/threeplus4.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 5', '/static/audio/math/threeplus5.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 6', '/static/audio/math/threeplus6.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 7', '/static/audio/math/threeplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 8', '/static/audio/math/threeplus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3 + 9', '/static/audio/math/threeplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4 + 4', '/static/audio/math/fourplus4.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4 + 5', '/static/audio/math/fourplus5.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4 + 6', '/static/audio/math/fourplus6.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4 + 7', '/static/audio/math/fourplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4 + 8', '/static/audio/math/fourplus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4 + 9', '/static/audio/math/fourplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5 + 5', '/static/audio/math/fiveplus5.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5 + 6', '/static/audio/math/fiveplus6.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5 + 7', '/static/audio/math/fiveplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5 + 8', '/static/audio/math/fiveplus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5 + 9', '/static/audio/math/fiveplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '6 + 6', '/static/audio/math/sixplus6.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '6 + 7', '/static/audio/math/sixplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '6 + 8', '/static/audio/math/sixplus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '6 + 9', '/static/audio/math/sixplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '7 + 7', '/static/audio/math/sevenplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '7 + 8', '/static/audio/math/sevenplus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '7 + 9', '/static/audio/math/sevenplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '8 + 8', '/static/audio/math/eightplus8.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '8 + 9', '/static/audio/math/eightplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '9 + 9', '/static/audio/math/nineplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '10 + 1', '/static/audio/math/tenplus1.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '12 + 5', '/static/audio/math/twelveplus5.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '20 + 5', '/static/audio/math/twentyplus5.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '13 + 12', '/static/audio/math/thirteenplus12.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '30 + 12', '/static/audio/math/thirtyplus12.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '14 + 7', '/static/audio/math/fourteenplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '40 + 7', '/static/audio/math/fortyplus7.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '15 + 10', '/static/audio/math/fifteenplus10.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '50 + 10', '/static/audio/math/fiftyplus10.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '16 + 11', '/static/audio/math/sixteenplus11.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '60 + 11', '/static/audio/math/sixtyplus11.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '17 + 4', '/static/audio/math/seventeenplus4.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '70 + 4', '/static/audio/math/seventyplus4.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '18 + 9', '/static/audio/math/eighteenplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '80 + 9', '/static/audio/math/eightyplus9.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '19 + 3', '/audio/math/19plus3.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '90 + 3', '/audio/math/90plus3.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Money', 'money') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'penny', '/audio/money/penny.mp3', NULL, '/images/money/penny.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'nickel', '/audio/money/nickel.mp3', NULL, '/images/money/nickel.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'dime', '/audio/money/dime.mp3', NULL, '/images/money/dime.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'quarter', '/audio/money/quarter.mp3', NULL, '/images/money/quarter.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'half-dollar', '/audio/money/halfdollar.mp3', NULL, '/images/money/halfdollar.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'dollar coins', '/audio/money/dollarcoins.mp3', NULL, '/images/money/dollarcoins.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'dollar bill', '/audio/money/dollarbill.mp3', NULL, '/images/money/dollarbill.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Money: Values', 'money-values') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1¢- 1 cent', '/audio/money/values/onecent.mp3', NULL, '/images/money/penny.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5¢- 5 cents', '/audio/money/values/fivecents.mp3', NULL, '/images/money/nickel.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '10¢- 10 cents', '/audio/money/values/tencents.mp3', NULL, '/images/money/dime.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '25¢- 25 cents', '/audio/money/values/twentyfivecents.mp3', NULL, '/images/money/quarter.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '50¢- 50 cents', '/audio/money/values/fiftycents.mp3', NULL, '/images/money/halfdollar.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '$1- 1 dollar', '/audio/money/values/onedollar.mp3', NULL, '/images/money/dollarcoins.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'The Alphabet: Capital Letters', 'the-alphabet-capital-letters') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'A', '/audio/alphabet/CapA.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'B', '/audio/alphabet/CapB.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'C', '/audio/alphabet/CapC.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'D', '/audio/alphabet/CapD.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'E', '/audio/alphabet/CapE.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'F', '/audio/alphabet/CapF.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'G', '/audio/alphabet/CapG.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'H', '/audio/alphabet/CapH.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'I', '/audio/alphabet/CapI.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'J', '/audio/alphabet/CapJ.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'K', '/audio/alphabet/CapK.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'L', '/audio/alphabet/CapL.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'M', '/audio/alphabet/CapM.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'N', '/audio/alphabet/CapN.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'O', '/audio/alphabet/CapO.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'P', '/audio/alphabet/CapP.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Q', '/audio/alphabet/CapQ.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'R', '/audio/alphabet/CapR.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'S', '/audio/alphabet/CapS.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'T', '/audio/alphabet/CapT.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'U', '/audio/alphabet/CapU.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'V', '/audio/alphabet/CapV.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'W', '/audio/alphabet/CapW.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'X', '/audio/alphabet/CapX.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Y', '/audio/alphabet/CapY.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Z', '/audio/alphabet/CapZ.mp3', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'The Alphabet: Small Letters', 'the-alphabet-small-letters') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'a', '/audio/alphabet/smalla.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'b', '/audio/alphabet/smallb.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'c', '/audio/alphabet/smallc.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'd', '/audio/alphabet/smalld.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'e', '/audio/alphabet/smalle.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'f', '/audio/alphabet/smallf.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'g', '/audio/alphabet/smallg.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'h', '/audio/alphabet/smallh.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'i', '/audio/alphabet/smalli.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'j', '/audio/alphabet/smallj.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'k', '/audio/alphabet/smallk.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'l', '/audio/alphabet/smalll.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'm', '/audio/alphabet/smallm.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'n', '/audio/alphabet/smalln.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'o', '/audio/alphabet/smallo.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'p', '/audio/alphabet/smallp.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'q', '/audio/alphabet/smallq.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'r', '/audio/alphabet/smallr.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 's', '/audio/alphabet/smalls.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 't', '/audio/alphabet/smallt.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'u', '/audio/alphabet/smallu.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'v', '/audio/alphabet/smallv.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'w', '/audio/alphabet/smallw.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'x', '/audio/alphabet/smallx.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'y', '/audio/alphabet/smally.mp3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'z', '/audio/alphabet/smallz.mp3', NULL, NULL);
END $$
