DO $$
DECLARE CategoryID integer;
BEGIN
INSERT INTO "Category" (type, title, slug) VALUES('color', 'Colors', 'colors') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'black', 'https://quizlet.com/tts/en.mp3?v=14&b=YmxhY2s&s=7ZwLA-Dh', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'white', 'https://quizlet.com/tts/en.mp3?v=14&b=d2hpdGU&s=QT.PyRQh', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'red', 'https://quizlet.com/tts/en.mp3?v=14&b=cmVk&s=iTuiQOtu', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'yellow', 'https://quizlet.com/tts/en.mp3?v=14&b=eWVsbG93&s=ZlXBmNWF', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'green', 'https://quizlet.com/tts/en.mp3?v=14&b=Z3JlZW4&s=ukGflW9g', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'purple', 'https://quizlet.com/tts/en.mp3?v=14&b=cHVycGxl&s=8FtWCj5b', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'blue', 'https://quizlet.com/tts/en.mp3?v=14&b=Ymx1ZQ&s=YWOexj-Y', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'orange', 'https://quizlet.com/tts/en.mp3?v=14&b=b3Jhbmdl&s=SlEzyRZI', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'pink', 'https://quizlet.com/tts/en.mp3?v=14&b=cGluaw&s=XInq7Kr0', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Shapes', 'shapes') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'circle', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2lyY2xl&s=2Ic0ytbo', '/images/shapes/circle.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'square', 'https://quizlet.com/tts/en.mp3?v=14&b=c3F1YXJl&s=OVSPnPp1', '/images/shapes/square.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'triangle', 'https://quizlet.com/tts/en.mp3?v=14&b=dHJpYW5nbGU&s=HHVQ7f0C', '/images/shapes/triangle.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'rectangle', 'https://quizlet.com/tts/en.mp3?v=14&b=cmVjdGFuZ2xl&s=y4yOfL4y', '/images/shapes/rectangle.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'arrow', 'https://quizlet.com/tts/en.mp3?v=14&b=YXJyb3c&s=wLctKZXD', '/images/shapes/arrow.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'star', 'https://quizlet.com/tts/en.mp3?v=14&b=c3Rhcg&s=BSvD2FuO', '/images/shapes/star.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'cross', 'https://quizlet.com/tts/en.mp3?v=14&b=Y3Jvc3M&s=.JvPMUvm', '/images/shapes/cross.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'diamond', 'https://quizlet.com/tts/en.mp3?v=14&b=ZGlhbW9uZA&s=GLZBf5.Y', '/images/shapes/diamond.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'heart', 'https://quizlet.com/tts/en.mp3?v=14&b=aGVhcnQ&s=3zVIiLMS', '/images/shapes/heart.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'hexagon', 'https://quizlet.com/tts/en.mp3?v=14&b=aGV4YWdvbg&s=Nsjenk0r', '/images/shapes/hexagon.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'moon', 'https://quizlet.com/tts/en.mp3?v=14&b=bW9vbg&s=U.QJVNj4', '/images/shapes/moon.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'pentagon', 'https://quizlet.com/tts/en.mp3?v=14&b=cGVudGFnb24&s=kB3cbKd6', '/images/shapes/pentagon.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'octagon', 'https://quizlet.com/tts/en.mp3?v=14&b=b2N0YWdvbg&s=BrOK2MPY', '/images/shapes/octagon.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'oval', 'https://quizlet.com/tts/en.mp3?v=14&b=b3ZhbA&s=-rV.mYXS', '/images/shapes/oval.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'parallelogram', 'https://quizlet.com/tts/en.mp3?v=14&b=cGFyYWxsZWxvZ3JhbQ&s=uCftiSN1', '/images/shapes/parallelogram.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'trapezoid', 'https://quizlet.com/tts/en.mp3?v=14&b=dHJhcGV6b2lk&s=53ehoxzl', '/images/shapes/trapezoid.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Numbers', 'numbers') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '0', 'https://quizlet.com/tts/en.mp3?v=14&b=MA&s=r7M1AADb', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '1', 'https://quizlet.com/tts/en.mp3?v=14&b=MQ&s=0V733b7v', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2', 'https://quizlet.com/tts/en.mp3?v=14&b=Mg&s=.QxtoYf8', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '3', 'https://quizlet.com/tts/en.mp3?v=14&b=Mw&s=n7Sm9fvf', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '4', 'https://quizlet.com/tts/en.mp3?v=14&b=NA&s=SS7Tpaoh', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '5', 'https://quizlet.com/tts/en.mp3?v=14&b=NQ&s=8Ircxc.W', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '6', 'https://quizlet.com/tts/en.mp3?v=14&b=Ng&s=pV8hpKUt', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '11', 'https://quizlet.com/tts/en.mp3?v=14&b=MTE&s=hoSh4LCo', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '21', 'https://quizlet.com/tts/en.mp3?v=14&b=MjE&s=-eWi6TBl', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '99', 'https://quizlet.com/tts/en.mp3?v=14&b=OTk&s=H9vXoFo2', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '100', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAw&s=AG6wLeVH', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '1000', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAwMA&s=.2isHaZK', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '10,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAsMDAw&s=mnhV0NZB', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '100,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAwLDAwMA&s=FkqBSgaG', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '1,000,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MSwwMDAsMDAw&s=fvr0GK3m', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '1,000,000,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MSwwMDAsMDAwLDAwMA&s=6a25yL43', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '1,234,567,890', 'https://quizlet.com/tts/en.mp3?v=14&b=MSwyMzQsNTY3LDg5MA&s=BYi8tPjL', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Food: Fruit', 'food-fruit') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'apple', 'https://quizlet.com/tts/en.mp3?v=14&b=YXBwbGU&s=d6IjXeYj', '/images/food/fruit/apple.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'banana', 'https://quizlet.com/tts/en.mp3?v=14&b=YmFuYW5h&s=WIhF3CEa', '/images/food/fruit/banana.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'coconut', 'https://quizlet.com/tts/en.mp3?v=14&b=Y29jb251dA&s=WpDKH9qm', '/images/food/fruit/coconut.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'lemon', 'https://quizlet.com/tts/en.mp3?v=14&b=bGVtb24&s=Wa-UppdA', '/images/food/fruit/lemon.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'pineapple', 'https://quizlet.com/tts/en.mp3?v=14&b=cGluZWFwcGxl&s=SwEBlJaL', '/images/food/fruit/pineapple.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'strawberry', 'https://quizlet.com/tts/en.mp3?v=14&b=c3RyYXdiZXJyeQ&s=Te6cvv.z', '/images/food/fruit/strawberry.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'watermelon', 'https://quizlet.com/tts/en.mp3?v=14&b=d2F0ZXJtZWxvbg&s=ShkWBAT1', '/images/food/fruit/watermelon.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Food: Vegetables', 'food-vegetables') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'asparagus', 'https://quizlet.com/tts/en.mp3?v=14&b=YXNwYXJhZ3Vz&s=31rWPo08', '/images/food/vegetables/asparagus.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'bellpepper', 'https://quizlet.com/tts/en.mp3?v=14&b=YmVsbHBlcHBlcg&s=r-1OYAex', '/images/food/vegetables/bellpepper.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'broccoli', 'https://quizlet.com/tts/en.mp3?v=14&b=YnJvY2NvbGk&s=-QoMO-jq', '/images/food/vegetables/broccoli.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'cabbage', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2FiYmFnZQ&s=4Gxb2sFp', '/images/food/vegetables/cabbage.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'cauliflower', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2F1bGlmbG93ZXI&s=5k7RjF4l', '/images/food/vegetables/cauliflower.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'greenbeans', 'https://quizlet.com/tts/en.mp3?v=14&b=Z3JlZW5iZWFucw&s=C2CYvSSV', '/images/food/vegetables/greenbeans.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'onion', 'https://quizlet.com/tts/en.mp3?v=14&b=b25pb24&s=GPu7jBJG', '/images/food/vegetables/onion.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'spinach', 'https://quizlet.com/tts/en.mp3?v=14&b=c3BpbmFjaA&s=.UQnZMXs', '/images/food/vegetables/spinach.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'tomato', 'https://quizlet.com/tts/en.mp3?v=14&b=dG9tYXRv&s=KAP5pe2u', '/images/food/vegetables/tomato.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Activities', 'activities') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'sleep', 'https://quizlet.com/tts/en.mp3?v=14&b=c2xlZXA&s=l4T9yviX', '/images/activities/sleep.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'eat', 'https://quizlet.com/tts/en.mp3?v=14&b=ZWF0&s=UkzGFhxq', '/images/activities/eat.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'drink', 'https://quizlet.com/tts/en.mp3?v=14&b=ZHJpbms&s=smeFxjAk', '/images/activities/drink.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'walk', 'https://quizlet.com/tts/en.mp3?v=14&b=d2Fsaw&s=jy7cK6Bl', '/images/activities/walk.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'run', 'https://quizlet.com/tts/en.mp3?v=14&b=cnVu&s=-G8dlTFn', '/images/activities/run.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'jump', 'https://quizlet.com/tts/en.mp3?v=14&b=anVtcA&s=1c5uKNzC', '/images/activities/jump.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'sit', 'https://quizlet.com/tts/en.mp3?v=14&b=c2l0&s=74h.97.B', '/images/activities/sit.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'stand', 'https://quizlet.com/tts/en.mp3?v=14&b=c3RhbmQ&s=3nyvriLN', '/images/activities/stand.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'look', 'https://quizlet.com/tts/en.mp3?v=14&b=bG9vaw&s=wlCzfAFT', '/images/activities/look-see.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'listen', 'https://quizlet.com/tts/en.mp3?v=14&b=bGlzdGVu&s=pop5czcY', '/images/activities/listen-hear.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'speak', 'https://quizlet.com/tts/en.mp3?v=14&b=c3BlYWs&s=P2w9fYFx', '/images/activities/speak-talk-say.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Days', 'days') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Sunday', 'https://quizlet.com/tts/en.mp3?v=14&b=U3VuZGF5&s=D5.TfTWy', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Monday', 'https://quizlet.com/tts/en.mp3?v=14&b=TW9uZGF5&s=A4t1WtVg', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Tuesday', 'https://quizlet.com/tts/en.mp3?v=14&b=VHVlc2RheQ&s=aQOxsiBR', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Wednesday', 'https://quizlet.com/tts/en.mp3?v=14&b=V2VkbmVzZGF5&s=tKWOyWRt', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Thursday', 'https://quizlet.com/tts/en.mp3?v=14&b=VGh1cnNkYXk&s=6137raV-', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Friday', 'https://quizlet.com/tts/en.mp3?v=14&b=RnJpZGF5&s=8y3sSf28', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Saturday', 'https://quizlet.com/tts/en.mp3?v=14&b=U2F0dXJkYXk&s=dNdpoE43', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Months', 'months') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'January', 'https://quizlet.com/tts/en.mp3?v=14&b=SmFudWFyeQ&s=e6yPaTiI', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'February', 'https://quizlet.com/tts/en.mp3?v=14&b=RmVicnVhcnk&s=EbrCuwZ9', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'March', 'https://quizlet.com/tts/en.mp3?v=14&b=TWFyY2g&s=xIzJO2YU', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'April', 'https://quizlet.com/tts/en.mp3?v=14&b=QXByaWw&s=Z8XqEf9j', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'May', 'https://quizlet.com/tts/en.mp3?v=14&b=TWF5&s=JKQ.Qh80', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'June', 'https://quizlet.com/tts/en.mp3?v=14&b=SnVuZQ&s=Lv0OdwGI', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'July', 'https://quizlet.com/tts/en.mp3?v=14&b=SnVseQ&s=frO9UUI2', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'August', 'https://quizlet.com/tts/en.mp3?v=14&b=QXVndXN0&s=OCAvfAZS', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'September', 'https://quizlet.com/tts/en.mp3?v=14&b=U2VwdGVtYmVy&s=QXrV8ytZ', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'October', 'https://quizlet.com/tts/en.mp3?v=14&b=T2N0b2Jlcg&s=4VHs7-X6', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'November', 'https://quizlet.com/tts/en.mp3?v=14&b=Tm92ZW1iZXI&s=lsIQJVUt', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'December', 'https://quizlet.com/tts/en.mp3?v=14&b=RGVjZW1iZXI&s=QJqCNXk9', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Seasons', 'seasons') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'spring', 'https://quizlet.com/tts/en.mp3?v=14&b=c3ByaW5n&s=suPtWtCP', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'summer', 'https://quizlet.com/tts/en.mp3?v=14&b=c3VtbWVy&s=OMkOmpOe', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'autumn', 'https://quizlet.com/tts/en.mp3?v=14&b=YXV0dW1u&s=ZjI-8OTu', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'winter', 'https://quizlet.com/tts/en.mp3?v=14&b=d2ludGVy&s=k4yvBY4A', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Weather', 'weather') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'sunny', 'https://quizlet.com/tts/en.mp3?v=14&b=c3Vubnk&s=ogqLo7mt', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'cloudy', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2xvdWR5&s=MRUfKOF8', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'foggy', 'https://quizlet.com/tts/en.mp3?v=14&b=Zm9nZ3k&s=mmY58pr6', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'smoggy', 'https://quizlet.com/tts/en.mp3?v=14&b=c21vZ2d5&s=e8iPppSX', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'rainy', 'https://quizlet.com/tts/en.mp3?v=14&b=cmFpbnk&s=8AQ6v9nW', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'windy', 'https://quizlet.com/tts/en.mp3?v=14&b=d2luZHk&s=DqodMHFM', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'snowy', 'https://quizlet.com/tts/en.mp3?v=14&b=c25vd3k&s=1Bt-ZrQr', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Temperature', 'temperature') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'hot', 'https://quizlet.com/tts/en.mp3?v=14&b=aG90&s=cnX5KKde', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'warm', 'https://quizlet.com/tts/en.mp3?v=14&b=d2FybQ&s=ng8SpsvO', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'cool', 'https://quizlet.com/tts/en.mp3?v=14&b=Y29vbA&s=W7Z02Q2C', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'cold', 'https://quizlet.com/tts/en.mp3?v=14&b=Y29sZA&s=bW4Yeg0P', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Math', 'math') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 3', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDM&s=YbXBjug1', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 4', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDQ&s=pWYiFOcp', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 5', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDU&s=VwulJr9k', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 6', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDY&s=gI75e1rr', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 7', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDc&s=.RnHJgcm', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 8', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDg&s=Jhul9SxF', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 9', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDk&s=yhd7wF-y', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 10', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDEw&s=ICqYt-WO', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 11', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDEx&s=F8uR0vfj', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 13', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDEz&s=Op0m92Z0', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 14', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE0&s=fnVzLn7-', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 15', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE1&s=oroajR-J', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 16', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE2&s=2Ed4rY.-', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 18', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE4&s=gMzOSbKV', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '2 + 19', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE5&s=P-lo.Vxq', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '19 + 3', 'https://quizlet.com/tts/en.mp3?v=14&b=MTkgKyAz&s=Fz2gbtA8', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, '90 + 3', 'https://quizlet.com/tts/en.mp3?v=14&b=OTAgKyAz&s=3rtRWGJK', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Money', 'money') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'penny', 'https://quizlet.com/tts/en.mp3?v=14&b=cGVubnk&s=brfm9YZ6', '/images/money/penny.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'nickel', 'https://quizlet.com/tts/en.mp3?v=14&b=bmlja2Vs&s=Im9lXDzf', '/images/money/nickel.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'dime', 'https://quizlet.com/tts/en.mp3?v=14&b=ZGltZQ&s=b6ckrkfM', '/images/money/dime.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'quarter', 'https://quizlet.com/tts/en.mp3?v=14&b=cXVhcnRlcg&s=RkhWAA.S', '/images/money/quarter.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'half-dollar', 'https://quizlet.com/tts/en.mp3?v=14&b=aGFsZi1kb2xsYXI&s=q5TMUwsw', '/images/money/halfdollar.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'dollar coins', 'https://quizlet.com/tts/en.mp3?v=14&b=ZG9sbGFyIGNvaW5z&s=mzZHahAp', '/images/money/dollarcoins.png');
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'dollar bill', 'https://quizlet.com/tts/en.mp3?v=14&b=ZG9sbGFyIGJpbGw&s=SZeZt3.6', '/images/money/dollarbill.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'The Alphabet: Capital Letters', 'the-alphabet-capital-letters') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'A', 'https://quizlet.com/tts/en.mp3?v=14&b=QQ&s=V1yTH95T', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'B', 'https://quizlet.com/tts/en.mp3?v=14&b=Qg&s=.W5089WA', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'C', 'https://quizlet.com/tts/en.mp3?v=14&b=Qw&s=XPi2fo7F', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'D', 'https://quizlet.com/tts/en.mp3?v=14&b=RA&s=T4A5wd3C', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'E', 'https://quizlet.com/tts/en.mp3?v=14&b=RQ&s=GfzF1u.g', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'F', 'https://quizlet.com/tts/en.mp3?v=14&b=Rg&s=75pPVrU7', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'G', 'https://quizlet.com/tts/en.mp3?v=14&b=Rw&s=XseuHZsK', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'H', 'https://quizlet.com/tts/en.mp3?v=14&b=SA&s=x6J9Wxnr', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'I', 'https://quizlet.com/tts/en.mp3?v=14&b=SQ&s=7.6I4OZ8', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'J', 'https://quizlet.com/tts/en.mp3?v=14&b=Sg&s=B.hsfGAG', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'K', 'https://quizlet.com/tts/en.mp3?v=14&b=Sw&s=h-bAChjc', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'L', 'https://quizlet.com/tts/en.mp3?v=14&b=TA&s=RAoCArx.', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'M', 'https://quizlet.com/tts/en.mp3?v=14&b=TQ&s=IZX9v0nv', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'N', 'https://quizlet.com/tts/en.mp3?v=14&b=Tg&s=v3p8LH97', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'O', 'https://quizlet.com/tts/en.mp3?v=14&b=Tw&s=x1BFrBJF', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'P', 'https://quizlet.com/tts/en.mp3?v=14&b=UA&s=Q7n0Racr', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Q', 'https://quizlet.com/tts/en.mp3?v=14&b=UQ&s=k3.pb.2a', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'R', 'https://quizlet.com/tts/en.mp3?v=14&b=Ug&s=ispoWAqh', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'S', 'https://quizlet.com/tts/en.mp3?v=14&b=Uw&s=Ue6WR7fz', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'T', 'https://quizlet.com/tts/en.mp3?v=14&b=VA&s=NeXRzrRf', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'U', 'https://quizlet.com/tts/en.mp3?v=14&b=VQ&s=ommevOAL', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'V', 'https://quizlet.com/tts/en.mp3?v=14&b=Vg&s=FzxnyVMG', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'W', 'https://quizlet.com/tts/en.mp3?v=14&b=Vw&s=jsWyyA-s', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'X', 'https://quizlet.com/tts/en.mp3?v=14&b=WA&s=uwfqZkBB', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Y', 'https://quizlet.com/tts/en.mp3?v=14&b=WQ&s=IvpkpJ.i', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'Z', 'https://quizlet.com/tts/en.mp3?v=14&b=Wg&s=vKQqelIQ', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'The Alphabet: Small Letters', 'the-alphabet-small-letters') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'a', 'https://quizlet.com/tts/en.mp3?v=14&b=YQ&s=F4Z2BsRW', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'b', 'https://quizlet.com/tts/en.mp3?v=14&b=Yg&s=3tPypMLX', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'c', 'https://quizlet.com/tts/en.mp3?v=14&b=Yw&s=yBLDYzuq', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'd', 'https://quizlet.com/tts/en.mp3?v=14&b=ZA&s=LA.sOv3V', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'e', 'https://quizlet.com/tts/en.mp3?v=14&b=ZQ&s=AoxS6bVo', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'f', 'https://quizlet.com/tts/en.mp3?v=14&b=Zg&s=NJ05SXG7', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'g', 'https://quizlet.com/tts/en.mp3?v=14&b=Zw&s=cHfJyL3h', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'h', 'https://quizlet.com/tts/en.mp3?v=14&b=aA&s=kNEjK6K2', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'i', 'https://quizlet.com/tts/en.mp3?v=14&b=aQ&s=-Zh8pVZh', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'j', 'https://quizlet.com/tts/en.mp3?v=14&b=ag&s=G-pXp5St', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'k', 'https://quizlet.com/tts/en.mp3?v=14&b=aw&s=KdP1eH39', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'l', 'https://quizlet.com/tts/en.mp3?v=14&b=bA&s=Y6z8321-', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'm', 'https://quizlet.com/tts/en.mp3?v=14&b=bQ&s=1kMfYEV3', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'n', 'https://quizlet.com/tts/en.mp3?v=14&b=bg&s=Z.iO5fjq', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'o', 'https://quizlet.com/tts/en.mp3?v=14&b=bw&s=aWw2dnV0', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'p', 'https://quizlet.com/tts/en.mp3?v=14&b=cA&s=mtujl1t2', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'q', 'https://quizlet.com/tts/en.mp3?v=14&b=cQ&s=pjS2.ZRM', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'r', 'https://quizlet.com/tts/en.mp3?v=14&b=cg&s=dYR4oONM', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 's', 'https://quizlet.com/tts/en.mp3?v=14&b=cw&s=FIZ36ME.', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 't', 'https://quizlet.com/tts/en.mp3?v=14&b=dA&s=jVV74c0S', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'u', 'https://quizlet.com/tts/en.mp3?v=14&b=dQ&s=EgYdQMKJ', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'v', 'https://quizlet.com/tts/en.mp3?v=14&b=dg&s=EuImLCop', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'w', 'https://quizlet.com/tts/en.mp3?v=14&b=dw&s=EpfupPDp', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'x', 'https://quizlet.com/tts/en.mp3?v=14&b=eA&s=c-FvdQRf', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'y', 'https://quizlet.com/tts/en.mp3?v=14&b=eQ&s=lBSw5kA1', NULL);
INSERT INTO "Question" (category_id, text, audio, image) VALUES(CategoryID, 'z', 'https://quizlet.com/tts/en.mp3?v=14&b=eg&s=kEFW8HFC', NULL);
END $$
