DO $$
DECLARE CategoryID integer;
BEGIN
INSERT INTO "Category" (type, title, slug) VALUES('color', 'Colors', 'colors') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'black', 'https://quizlet.com/tts/en.mp3?v=14&b=YmxhY2s&s=7ZwLA-Dh', 'black', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'white', 'https://quizlet.com/tts/en.mp3?v=14&b=d2hpdGU&s=QT.PyRQh', 'white', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'red', 'https://quizlet.com/tts/en.mp3?v=14&b=cmVk&s=iTuiQOtu', 'red', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'yellow', 'https://quizlet.com/tts/en.mp3?v=14&b=eWVsbG93&s=ZlXBmNWF', 'yellow', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'green', 'https://quizlet.com/tts/en.mp3?v=14&b=Z3JlZW4&s=ukGflW9g', 'green', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'purple', 'https://quizlet.com/tts/en.mp3?v=14&b=cHVycGxl&s=8FtWCj5b', 'purple', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'blue', 'https://quizlet.com/tts/en.mp3?v=14&b=Ymx1ZQ&s=YWOexj-Y', 'blue', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'orange', 'https://quizlet.com/tts/en.mp3?v=14&b=b3Jhbmdl&s=SlEzyRZI', 'orange', NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'pink', 'https://quizlet.com/tts/en.mp3?v=14&b=cGluaw&s=XInq7Kr0', 'pink', NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Shapes', 'shapes') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'circle', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2lyY2xl&s=2Ic0ytbo', NULL, '/images/shapes/circle.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'square', 'https://quizlet.com/tts/en.mp3?v=14&b=c3F1YXJl&s=OVSPnPp1', NULL, '/images/shapes/square.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'triangle', 'https://quizlet.com/tts/en.mp3?v=14&b=dHJpYW5nbGU&s=HHVQ7f0C', NULL, '/images/shapes/triangle.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'rectangle', 'https://quizlet.com/tts/en.mp3?v=14&b=cmVjdGFuZ2xl&s=y4yOfL4y', NULL, '/images/shapes/rectangle.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'arrow', 'https://quizlet.com/tts/en.mp3?v=14&b=YXJyb3c&s=wLctKZXD', NULL, '/images/shapes/arrow.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'star', 'https://quizlet.com/tts/en.mp3?v=14&b=c3Rhcg&s=BSvD2FuO', NULL, '/images/shapes/star.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cross', 'https://quizlet.com/tts/en.mp3?v=14&b=Y3Jvc3M&s=.JvPMUvm', NULL, '/images/shapes/cross.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'diamond', 'https://quizlet.com/tts/en.mp3?v=14&b=ZGlhbW9uZA&s=GLZBf5.Y', NULL, '/images/shapes/diamond.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'heart', 'https://quizlet.com/tts/en.mp3?v=14&b=aGVhcnQ&s=3zVIiLMS', NULL, '/images/shapes/heart.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'hexagon', 'https://quizlet.com/tts/en.mp3?v=14&b=aGV4YWdvbg&s=Nsjenk0r', NULL, '/images/shapes/hexagon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'moon', 'https://quizlet.com/tts/en.mp3?v=14&b=bW9vbg&s=U.QJVNj4', NULL, '/images/shapes/moon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'pentagon', 'https://quizlet.com/tts/en.mp3?v=14&b=cGVudGFnb24&s=kB3cbKd6', NULL, '/images/shapes/pentagon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'octagon', 'https://quizlet.com/tts/en.mp3?v=14&b=b2N0YWdvbg&s=BrOK2MPY', NULL, '/images/shapes/octagon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'oval', 'https://quizlet.com/tts/en.mp3?v=14&b=b3ZhbA&s=-rV.mYXS', NULL, '/images/shapes/oval.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'parallelogram', 'https://quizlet.com/tts/en.mp3?v=14&b=cGFyYWxsZWxvZ3JhbQ&s=uCftiSN1', NULL, '/images/shapes/parallelogram.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'trapezoid', 'https://quizlet.com/tts/en.mp3?v=14&b=dHJhcGV6b2lk&s=53ehoxzl', NULL, '/images/shapes/trapezoid.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Numbers', 'numbers') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '0', 'https://quizlet.com/tts/en.mp3?v=14&b=MA&s=r7M1AADb', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1', 'https://quizlet.com/tts/en.mp3?v=14&b=MQ&s=0V733b7v', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2', 'https://quizlet.com/tts/en.mp3?v=14&b=Mg&s=.QxtoYf8', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '3', 'https://quizlet.com/tts/en.mp3?v=14&b=Mw&s=n7Sm9fvf', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '4', 'https://quizlet.com/tts/en.mp3?v=14&b=NA&s=SS7Tpaoh', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '5', 'https://quizlet.com/tts/en.mp3?v=14&b=NQ&s=8Ircxc.W', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '6', 'https://quizlet.com/tts/en.mp3?v=14&b=Ng&s=pV8hpKUt', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '11', 'https://quizlet.com/tts/en.mp3?v=14&b=MTE&s=hoSh4LCo', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '21', 'https://quizlet.com/tts/en.mp3?v=14&b=MjE&s=-eWi6TBl', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '99', 'https://quizlet.com/tts/en.mp3?v=14&b=OTk&s=H9vXoFo2', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '100', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAw&s=AG6wLeVH', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1000', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAwMA&s=.2isHaZK', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '10,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAsMDAw&s=mnhV0NZB', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '100,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MTAwLDAwMA&s=FkqBSgaG', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1,000,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MSwwMDAsMDAw&s=fvr0GK3m', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1,000,000,000', 'https://quizlet.com/tts/en.mp3?v=14&b=MSwwMDAsMDAwLDAwMA&s=6a25yL43', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '1,234,567,890', 'https://quizlet.com/tts/en.mp3?v=14&b=MSwyMzQsNTY3LDg5MA&s=BYi8tPjL', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Food: Fruit', 'food-fruit') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'apple', 'https://quizlet.com/tts/en.mp3?v=14&b=YXBwbGU&s=d6IjXeYj', NULL, '/images/food/fruit/apple.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'banana', 'https://quizlet.com/tts/en.mp3?v=14&b=YmFuYW5h&s=WIhF3CEa', NULL, '/images/food/fruit/banana.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'coconut', 'https://quizlet.com/tts/en.mp3?v=14&b=Y29jb251dA&s=WpDKH9qm', NULL, '/images/food/fruit/coconut.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'lemon', 'https://quizlet.com/tts/en.mp3?v=14&b=bGVtb24&s=Wa-UppdA', NULL, '/images/food/fruit/lemon.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'pineapple', 'https://quizlet.com/tts/en.mp3?v=14&b=cGluZWFwcGxl&s=SwEBlJaL', NULL, '/images/food/fruit/pineapple.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'strawberry', 'https://quizlet.com/tts/en.mp3?v=14&b=c3RyYXdiZXJyeQ&s=Te6cvv.z', NULL, '/images/food/fruit/strawberry.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'watermelon', 'https://quizlet.com/tts/en.mp3?v=14&b=d2F0ZXJtZWxvbg&s=ShkWBAT1', NULL, '/images/food/fruit/watermelon.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Food: Vegetables', 'food-vegetables') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'asparagus', 'https://quizlet.com/tts/en.mp3?v=14&b=YXNwYXJhZ3Vz&s=31rWPo08', NULL, '/images/food/vegetables/asparagus.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'bellpepper', 'https://quizlet.com/tts/en.mp3?v=14&b=YmVsbHBlcHBlcg&s=r-1OYAex', NULL, '/images/food/vegetables/bellpepper.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'broccoli', 'https://quizlet.com/tts/en.mp3?v=14&b=YnJvY2NvbGk&s=-QoMO-jq', NULL, '/images/food/vegetables/broccoli.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cabbage', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2FiYmFnZQ&s=4Gxb2sFp', NULL, '/images/food/vegetables/cabbage.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cauliflower', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2F1bGlmbG93ZXI&s=5k7RjF4l', NULL, '/images/food/vegetables/cauliflower.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'greenbeans', 'https://quizlet.com/tts/en.mp3?v=14&b=Z3JlZW5iZWFucw&s=C2CYvSSV', NULL, '/images/food/vegetables/greenbeans.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'onion', 'https://quizlet.com/tts/en.mp3?v=14&b=b25pb24&s=GPu7jBJG', NULL, '/images/food/vegetables/onion.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'spinach', 'https://quizlet.com/tts/en.mp3?v=14&b=c3BpbmFjaA&s=.UQnZMXs', NULL, '/images/food/vegetables/spinach.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'tomato', 'https://quizlet.com/tts/en.mp3?v=14&b=dG9tYXRv&s=KAP5pe2u', NULL, '/images/food/vegetables/tomato.png');
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Activities', 'activities') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'sleep', 'https://quizlet.com/tts/en.mp3?v=14&b=c2xlZXA&s=l4T9yviX', NULL, '/images/activities/sleep.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'eat', 'https://quizlet.com/tts/en.mp3?v=14&b=ZWF0&s=UkzGFhxq', NULL, '/images/activities/eat.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'drink', 'https://quizlet.com/tts/en.mp3?v=14&b=ZHJpbms&s=smeFxjAk', NULL, '/images/activities/drink.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'walk', 'https://quizlet.com/tts/en.mp3?v=14&b=d2Fsaw&s=jy7cK6Bl', NULL, '/images/activities/walk.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'run', 'https://quizlet.com/tts/en.mp3?v=14&b=cnVu&s=-G8dlTFn', NULL, '/images/activities/run.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'jump', 'https://quizlet.com/tts/en.mp3?v=14&b=anVtcA&s=1c5uKNzC', NULL, '/images/activities/jump.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'sit', 'https://quizlet.com/tts/en.mp3?v=14&b=c2l0&s=74h.97.B', NULL, '/images/activities/sit.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'stand', 'https://quizlet.com/tts/en.mp3?v=14&b=c3RhbmQ&s=3nyvriLN', NULL, '/images/activities/stand.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'look', 'https://quizlet.com/tts/en.mp3?v=14&b=bG9vaw&s=wlCzfAFT', NULL, '/images/activities/look-see.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'listen', 'https://quizlet.com/tts/en.mp3?v=14&b=bGlzdGVu&s=pop5czcY', NULL, '/images/activities/listen-hear.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'speak', 'https://quizlet.com/tts/en.mp3?v=14&b=c3BlYWs&s=P2w9fYFx', NULL, '/images/activities/speak-talk-say.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Days', 'days') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Sunday', 'https://quizlet.com/tts/en.mp3?v=14&b=U3VuZGF5&s=D5.TfTWy', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Monday', 'https://quizlet.com/tts/en.mp3?v=14&b=TW9uZGF5&s=A4t1WtVg', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Tuesday', 'https://quizlet.com/tts/en.mp3?v=14&b=VHVlc2RheQ&s=aQOxsiBR', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Wednesday', 'https://quizlet.com/tts/en.mp3?v=14&b=V2VkbmVzZGF5&s=tKWOyWRt', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Thursday', 'https://quizlet.com/tts/en.mp3?v=14&b=VGh1cnNkYXk&s=6137raV-', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Friday', 'https://quizlet.com/tts/en.mp3?v=14&b=RnJpZGF5&s=8y3sSf28', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Saturday', 'https://quizlet.com/tts/en.mp3?v=14&b=U2F0dXJkYXk&s=dNdpoE43', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Months', 'months') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'January', 'https://quizlet.com/tts/en.mp3?v=14&b=SmFudWFyeQ&s=e6yPaTiI', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'February', 'https://quizlet.com/tts/en.mp3?v=14&b=RmVicnVhcnk&s=EbrCuwZ9', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'March', 'https://quizlet.com/tts/en.mp3?v=14&b=TWFyY2g&s=xIzJO2YU', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'April', 'https://quizlet.com/tts/en.mp3?v=14&b=QXByaWw&s=Z8XqEf9j', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'May', 'https://quizlet.com/tts/en.mp3?v=14&b=TWF5&s=JKQ.Qh80', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'June', 'https://quizlet.com/tts/en.mp3?v=14&b=SnVuZQ&s=Lv0OdwGI', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'July', 'https://quizlet.com/tts/en.mp3?v=14&b=SnVseQ&s=frO9UUI2', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'August', 'https://quizlet.com/tts/en.mp3?v=14&b=QXVndXN0&s=OCAvfAZS', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'September', 'https://quizlet.com/tts/en.mp3?v=14&b=U2VwdGVtYmVy&s=QXrV8ytZ', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'October', 'https://quizlet.com/tts/en.mp3?v=14&b=T2N0b2Jlcg&s=4VHs7-X6', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'November', 'https://quizlet.com/tts/en.mp3?v=14&b=Tm92ZW1iZXI&s=lsIQJVUt', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'December', 'https://quizlet.com/tts/en.mp3?v=14&b=RGVjZW1iZXI&s=QJqCNXk9', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Seasons', 'seasons') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'spring', 'https://quizlet.com/tts/en.mp3?v=14&b=c3ByaW5n&s=suPtWtCP', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'summer', 'https://quizlet.com/tts/en.mp3?v=14&b=c3VtbWVy&s=OMkOmpOe', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'autumn', 'https://quizlet.com/tts/en.mp3?v=14&b=YXV0dW1u&s=ZjI-8OTu', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'winter', 'https://quizlet.com/tts/en.mp3?v=14&b=d2ludGVy&s=k4yvBY4A', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Weather', 'weather') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'sunny', 'https://quizlet.com/tts/en.mp3?v=14&b=c3Vubnk&s=ogqLo7mt', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cloudy', 'https://quizlet.com/tts/en.mp3?v=14&b=Y2xvdWR5&s=MRUfKOF8', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'foggy', 'https://quizlet.com/tts/en.mp3?v=14&b=Zm9nZ3k&s=mmY58pr6', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'smoggy', 'https://quizlet.com/tts/en.mp3?v=14&b=c21vZ2d5&s=e8iPppSX', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'rainy', 'https://quizlet.com/tts/en.mp3?v=14&b=cmFpbnk&s=8AQ6v9nW', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'windy', 'https://quizlet.com/tts/en.mp3?v=14&b=d2luZHk&s=DqodMHFM', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'snowy', 'https://quizlet.com/tts/en.mp3?v=14&b=c25vd3k&s=1Bt-ZrQr', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Temperature', 'temperature') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'hot', 'https://quizlet.com/tts/en.mp3?v=14&b=aG90&s=cnX5KKde', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'warm', 'https://quizlet.com/tts/en.mp3?v=14&b=d2FybQ&s=ng8SpsvO', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cool', 'https://quizlet.com/tts/en.mp3?v=14&b=Y29vbA&s=W7Z02Q2C', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'cold', 'https://quizlet.com/tts/en.mp3?v=14&b=Y29sZA&s=bW4Yeg0P', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'Math', 'math') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 3', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDM&s=YbXBjug1', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 4', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDQ&s=pWYiFOcp', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 5', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDU&s=VwulJr9k', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 6', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDY&s=gI75e1rr', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 7', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDc&s=.RnHJgcm', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 8', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDg&s=Jhul9SxF', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 9', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDk&s=yhd7wF-y', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 10', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDEw&s=ICqYt-WO', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 11', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDEx&s=F8uR0vfj', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 13', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDEz&s=Op0m92Z0', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 14', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE0&s=fnVzLn7-', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 15', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE1&s=oroajR-J', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 16', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE2&s=2Ed4rY.-', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 18', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE4&s=gMzOSbKV', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '2 + 19', 'https://quizlet.com/tts/en.mp3?v=14&b=MiArIDE5&s=P-lo.Vxq', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '19 + 3', 'https://quizlet.com/tts/en.mp3?v=14&b=MTkgKyAz&s=Fz2gbtA8', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, '90 + 3', 'https://quizlet.com/tts/en.mp3?v=14&b=OTAgKyAz&s=3rtRWGJK', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('image', 'Money', 'money') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'penny', 'https://quizlet.com/tts/en.mp3?v=14&b=cGVubnk&s=brfm9YZ6', NULL, '/images/money/penny.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'nickel', 'https://quizlet.com/tts/en.mp3?v=14&b=bmlja2Vs&s=Im9lXDzf', NULL, '/images/money/nickel.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'dime', 'https://quizlet.com/tts/en.mp3?v=14&b=ZGltZQ&s=b6ckrkfM', NULL, '/images/money/dime.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'quarter', 'https://quizlet.com/tts/en.mp3?v=14&b=cXVhcnRlcg&s=RkhWAA.S', NULL, '/images/money/quarter.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'half-dollar', 'https://quizlet.com/tts/en.mp3?v=14&b=aGFsZi1kb2xsYXI&s=q5TMUwsw', NULL, '/images/money/halfdollar.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'dollar coins', 'https://quizlet.com/tts/en.mp3?v=14&b=ZG9sbGFyIGNvaW5z&s=mzZHahAp', NULL, '/images/money/dollarcoins.png');
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'dollar bill', 'https://quizlet.com/tts/en.mp3?v=14&b=ZG9sbGFyIGJpbGw&s=SZeZt3.6', NULL, '/images/money/dollarbill.png');
INSERT INTO "Category" (type, title, slug) VALUES('text', 'The Alphabet: Capital Letters', 'the-alphabet-capital-letters') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'A', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBB&s=5ec7maKv', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'B', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBC&s=FFzmocNb', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'C', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBD&s=cnn1L7sW', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'D', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBE&s=0nF7T8mM', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'E', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBF&s=mGEWohf2', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'F', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBG&s=piLyjRIx', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'G', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBH&s=1nVg0566', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'H', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBI&s=dZzDshhz', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'I', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBJ&s=CM4mlHnH', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'J', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBK&s=NDhEEhXc', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'K', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBL&s=bOGCJF45', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'L', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBM&s=W3DVbpjd', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'M', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBN&s=BTH9Zsnf', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'N', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBO&s=OfvoWpP.', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'O', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBP&s=ZJgmR6Nr', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'P', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBQ&s=82a3XMVI', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Q', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBR&s=cRa4InHQ', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'R', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBS&s=ZLqLq4tZ', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'S', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBT&s=Tw05DNJY', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'T', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBU&s=-s5YUjRu', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'U', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBV&s=Tv6OyNeg', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'V', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBW&s=iFhkwqZx', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'W', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBX&s=lHPYRtIJ', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'X', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBY&s=rUfSIJT3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Y', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBZ&s=Ogu5PLE3', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'Z', 'https://quizlet.com/tts/en.mp3?v=14&b=Q2FwaXRhbCBa&s=8hj0Dhd2', NULL, NULL);
INSERT INTO "Category" (type, title, slug) VALUES('text', 'The Alphabet: Small Letters', 'the-alphabet-small-letters') RETURNING id INTO CategoryID;
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'a', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgYQ&s=zImkXo08', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'b', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgYg&s=EVvwYj19', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'c', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgYw&s=bUQZoRCQ', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'd', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgZA&s=awa-NYdS', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'e', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgZQ&s=fe.FlO4u', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'f', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgZg&s=U0tdwv5C', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'g', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgZw&s=9SZVJ6Fz', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'h', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgaA&s=EsKzCEz6', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'i', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgaQ&s=s755zj63', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'j', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgag&s=ow3GrSNi', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'k', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgaw&s=FwaLkWHa', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'l', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgbA&s=raFjBxCW', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'm', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgbQ&s=iTn4qgNz', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'n', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgbg&s=ttXCEmno', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'o', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgbw&s=2kjgNofj', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'p', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgcA&s=E9GxgDoO', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'q', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgcQ&s=E.5ylpw8', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'r', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgcg&s=4qDNH4SP', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 's', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgcw&s=O2HS6G0u', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 't', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgdA&s=DO5iqILK', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'u', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgdQ&s=0oTIBSl8', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'v', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgdg&s=ODWEGqgv', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'w', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgdw&s=29WszgdX', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'x', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgeA&s=Y0WNSpyj', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'y', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgeQ&s=pNhmUdsL', NULL, NULL);
INSERT INTO "Question" (category_id, text, audio, color, image) VALUES(CategoryID, 'z', 'https://quizlet.com/tts/en.mp3?v=14&b=U21hbGwgeg&s=V0fG-EZi', NULL, NULL);
END $$
